experiment:
  name: utzappos50k/best
dataset:
  data_dir: ut-zap50k
  dataset: utzappos
  splitname: compositional-split-natural
model_params:
  model: LVAR
  emb_dim: 300
  emb_init: word2vec
  image_extractor: Wave-MLP
  train_only: true
MLP:
  obj_fclayers: 2
  obj_emb: [ 600,1024 ]
  attr_fclayers: 2
  attr_emb: [ 600,512 ]
  pair_fclayers: 2
  pair_emb: [ 600,512 ]
  dropout: true
  norm: true
  relu: true
Encoder:
  obj_nlayer: 4
  attr_nlayer: 4
  obj_nhead: 10
  attr_nhead: 10
training:
  batch_size: 128
  eval_val_every: 1
  alpha: 0.7
  beta: 0.3
  lr: 0.00002
  wd: 5.0e-05
  lrg: 5.0e-6 # Learning rete for image backbone if fine-tune the backbone
  max_epochs: 50
  test_batch_size: 32
  test_set: val
  topk: 1
  workers: 8
  update_features: Ture # Fine tune the image backbone